### ISSUE TITLE
Code styling

### ISSUE THREAD

**Issue by DenizUgur** [gpac/gpac#3087]
I've used the following tool to generate a `.clang-format` configuration. I'm opening this issue to start a conversation to find the configruation that would introduce the minimal diff.

https://github.com/mikr/whatstyle

```yaml
AlignAfterOpenBracket: DontAlign
AllowShortIfStatementsOnASingleLine: true
BraceWrapping:
  AfterFunction: true
  AfterStruct: true
BreakBeforeBinaryOperators: NonAssignment
BreakBeforeBraces: Custom
ColumnLimit: 0
ContinuationIndentWidth: 0
Cpp11BracedListStyle: false
MaxEmptyLinesToKeep: 2
ReflowComments: false
SkipMacroDefinitionBody: true
SpaceAfterCStyleCast: true
TabWidth: 2
UseTab: ForIndentation
```
